### ISSUE TITLE
Make Password optional

### ISSUE THREAD

**Issue by tony-caffe** [singleplatform-eng/ansible-users#14]
Hi,

 Can we change password to be optional if blank, a different setting for locking the account and then of course the hash option. Some users I dont want to manage passwords and I dont want to lock them out.

**Comment by bhardin** [comment]
👍

**Comment by tony-caffe** [comment]
I dont think this will ever be implemented. No response for a long time.

**Comment by bhardin** [comment]
They actually are optional if you have an SSH key. So, this fulfills my request.

**Comment by tony-caffe** [comment]
This is an improved/forked version of this one and locks the user when it is empty and allows hashed passwords: https://github.com/dphilpot/ansible-users

**Comment by ghost** [comment]
I believe this has been addressed as the password is currently optional. `!` is the module default when the `password` parameter is omitted.
