### ISSUE TITLE
put users into hash instead list

### ISSUE THREAD

**Issue by rudibatt** [singleplatform-eng/ansible-users#21]
Having hosts in multiple groups leads to the problem, that only the users from one group_vars file are considered. 
Some one else had the same problem before: https://groups.google.com/forum/#!msg/ansible-project/l7KIwiL5pIU/ox_DeA1y6BgJ

Would it be an option to put "users" into a hash instead of using a list, so it would be possible to define users in different group_vars (if "hash_behaviour = merge")?

**Comment by ghost** [comment]
I agree that using a hash is a bit cleaner and makes more sense when `hash_behaviour = merge`. However, I would imagine a good number of the role's users are not changing the default hash_behaviour, as the documentation [generally recommends not using this setting](http://docs.ansible.com/ansible/intro_configuration.html#hash-behaviour). Also, a change like this would require that most users refactor their user definitions.

For these reasons, I think making this change is currently not an option. However, if people disagree we can re-open this issue and think about making this change in a future release.

Although it's not a perfect solution, you could use list concatenation as an alternative.
