### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by crazydisi** [singleplatform-eng/ansible-users#23]
Hi mivok,

just as a info with the newest ansible (2.0.1.0) version we get  deprecation warnings.

example:
`[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{users}}'). This feature will be removed in a future
release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.`

**Comment by bhardin** [comment]
👍

**Comment by ghost** [comment]
Resolved in https://github.com/choglundsp/ansible-users/pull/31
