### ISSUE TITLE
Hiding sensitive data

### ISSUE THREAD

**Issue by eproxus** [singleplatform-eng/ansible-users#3]
When running with a list of users, the SSH keys are displayed in plaintext in the Ansible output per item. Is there any nice way to hide this data? We keep it in a vault file normally, so it is not so nice if it leaks out in some shell history/log somewhere.

**Comment by mivok** [comment]
The keys displayed are public, not private keys. While it would be nice to have the logs be a little less verbose, this isn't a security risk.

**Comment by eproxus** [comment]
That is of course true. I checked around and as long as all the data is in the items, I think there is no way to hide it currently.
