### ISSUE TITLE
repo migration

### ISSUE THREAD

**Issue by facastagnini** [singleplatform-eng/ansible-users#30]
@mivok  is no longer maintaining this repo.
There is a pile of PRs that never got merged, and he doesnt participate in the discussions.

I propose to move forward and use a fork mentioned here https://github.com/mivok/ansible-users/pull/26

Lets try to get together behind a single fork to get the benefits of the community :)

@bhardin, @choglundsp, @tony-caffe, @wzur , @akhon , @dphilpot, @trumant, @hahnicity, @lyletagawa, @gnarf, @olpia, @stucki, @rudibatt, @dphilpot 

You guys submitted PRs that never got merged, please share your thoughts.

**Comment by mivok** [comment]
Hi,

I would be happy to have a new maintainer take over this project. This was a small role developed for personal use and I no longer use ansible regularly. Let me know if there is anything I can do to facilitate the transfer to a new maintainer (E.g. I can transfer the repository if someone wishes to take over maintainership of the project).

**Comment by ghost** [comment]
@facastagnini  and @mivok,

As mentioned in the PR, we would be happy to take over maintenance of the
role. Again, please note the following differences:
- groups_to_create is now a list of dictionaries. This allows users to more
  easily specify a gid.
- Fixed with_items: deprecation warnings from Ansible 2+
- Items in the users list take a new attribute of profile for setting up
  custom shell profiles.

@mivok,

I think transferring ownership of the repo makes sense, but I believe I
will need to rename our existing fork to facilitate the transfer. Once the
transfer is complete, I will probably tag the repo as is before merging the
changes from our fork.

Let me know if this makes sense and I will rename our fork and we can move
forward with the transfer.

**Comment by mivok** [comment]
Sure, that sounds fine to me.

**Comment by ghost** [comment]
I've renamed our fork. Feel free to transfer the repo to @singleplatform-eng whenever.

**Comment by mivok** [comment]
So when I try to transfer it, I get the following:

> singleplatform-eng already has a repository in the mivok/ansible-users network and You don’t have admin rights to singleplatform-eng

I believe these are two separate issues:
- The existing fork might have to be deleted and not just renamed
- Admin access in the receiving organization is required to transfer a repository to an organization

Rather than give me admin access to singleplatform-eng, I can transfer the repository directly to you (choglundsp) and you can then transfer it into the organization (presumably you have admin access there). You would still have to address the fact that the fork already exists in the organization though.

Does that work?

**Comment by ghost** [comment]
yeah, that works. thanks.

**Comment by facastagnini** [comment]
Hey @mivok thanks for handing over the administration to keep the repo alive, there is a lot of people using this!

**Comment by ghost** [comment]
I've created a [v0.1.0 release](https://github.com/choglundsp/ansible-users/releases/tag/v0.1.0) which is the state of the codebase before the transfer. I will merge in the minor changes from the singleplatform-eng fork and work through the existing PRs and issues before creating another release.

**Comment by facastagnini** [comment]
@choglundsp let me know if you need help

**Comment by ghost** [comment]
Thanks, I think I've worked through most of it. I imagine there will likely be some problems that come out of this migration, so don't hesitate to open Issues for them.
