### ISSUE TITLE
update_password: always not idempotent? 

### ISSUE THREAD

**Issue by sjktje** [singleplatform-eng/ansible-users#46]
According to the README, update_password set to "always" will "update passwords if they differ," and is the default behaviour. The "user creation" task is always causing a change, however. Is this the intended behaviour? Should the line in the README be rephrased?

**Comment by ghost** [comment]
@sjktje The per-user `update_password` parameter should be idempotent as it just wrappers the underlying [user module](http://docs.ansible.com/ansible/user_module.html) functionality. In my tests `update_password: always`, as well as the absence of the parameter, is indeed idempotent. Would you mind sharing an example configuration in order for me to re-create the issue?

**Comment by ghost** [comment]
Closing this issue, feel free to re-open if you continue experiencing issues.
