### ISSUE TITLE
Add setting to delete associated home directory when deleting a user

### ISSUE THREAD

**Issue by colin-nolan** [singleplatform-eng/ansible-users#47]
This role currently enables users to be easily deleted but this action leaves behind the old user's home directory.

It would be good if there was an option to also remove home directories when deleting users.

**Comment by ghost** [comment]
Issue addressed in PR https://github.com/singleplatform-eng/ansible-users/pull/48 and released in [v1.2.3](https://github.com/singleplatform-eng/ansible-users/releases/tag/1.2.3)
