### ISSUE TITLE
Optional uid?

### ISSUE THREAD

**Issue by jonbrefe** [singleplatform-eng/ansible-users#50]
Is there a way to have the uid as optional? I have an environment in which sadly the uid are not unified under a single list. I tried to changed the code to skip this, but it didn't work for me
    uid: "{{item.uid if item.uid is defined else false| default(omit)}}"

I tried several times, no luck

**Comment by ghost** [comment]
I created a PR that should address the issue and it looks like travis checks have passed. Group creation also needed to be modified in order to accommodate this change.
