### ISSUE TITLE
Unable to compare role versions

### ISSUE THREAD

**Issue by o0Silas0o** [singleplatform-eng/ansible-users#58]
I was trying to download this Role using Ansible Galaxy and I got an error because the latest version number (1.2.6) is not in the same format as the rest (v1.2.x). Are you able to update the version number?

<img width="528" alt="Screen Shot 2019-03-15 at 10 35 06 AM" src="https://user-images.githubusercontent.com/838210/54434930-1fcaa800-470e-11e9-8757-03496b7fc13a.png">

**Comment by wwaltersp** [comment]
Sorry about that. I updated the release to have the v at the start of that version. Let me know if there are still issues and I can remove that release or tag a whole new release.

**Comment by o0Silas0o** [comment]
Thanks for the quick response. I am still seeing 1.2.6 in the version list within Ansible Galaxy without the 'v' prefix.

**Comment by wwaltersp** [comment]
I removed the old tag and reimported on galaxy. I see the v1.2.6 in the versions list now and no longer see 1.2.6, so give it a shot again.

**Comment by o0Silas0o** [comment]
Fantastic! It's working now.
